sudo: required
dist: bionic
language: go
go:
  - master
  - 1.13.x
  - 1.12.x

go_import_path: github.com/rh-messaging/shipshape

services:
  - docker

git:
  depth: 1

env:
  global:
    - KUBECONFIG=$HOME/.kube/config
    - KUBERNETES_VERSION=$(curl -k -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
    - GO111MODULE=on

before_install:
  # Setup kubectl
  - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBERNETES_VERSION}/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/

  # Get tools
  - export GO111MODULE=off; go get sigs.k8s.io/kind
  - echo "======"
  - export GOPATH=`go env GOPATH`
  - echo "go11module = ${GO111MODULE}"
  - echo "path = ${PATH}"
  - echo "gopath = ${GOPATH}"
  - echo "path = ${PATH}"
  - go get github.com/jfeliu007/goplantuml/parser
  - go get github.com/jfeliu007/goplantuml/cmd/goplantuml
  - cd $GOPATH/src/github.com/jfeliu007/goplantuml
  - go install ./...
  - cd -

  # Create a new Kubernetes cluster using KinD
  - kind create cluster
  - kubectl cluster-info

script:
  - export GO111MODULE=on
  - cd $GOPATH/src/github.com/rh-messaging/shipshape
  - make
  - make uml
  - make cluster-test

